# Generated by Django 5.2.6 on 2025-09-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_experience_created_at_experience_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='current',
        ),
    ]
